name = "sprocket"
version = "0.1.10"
description = "A library for building live views and real-time server components in Gleam"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
repository = { type = "github", user = "bitbldr", repo = "sprocket" }
links = [{ title = "Website", href = "https://sprocket.live" }]

# Modules that should be considered "internal" and will not be included in
# generated documentation. Note this currently only affects documentation;
# public types and functions defined in these modules are still public.
#
# Items in this list are "globs" that are matched against module names. See:
# https://docs.rs/glob/latest/glob/struct.Pattern.html
internal_modules = [
  "sprocket/internal/*",
  "sprocket/sprocket",
  "tools/*",
]
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.33"
gleam_http = "~> 3.5"
gleam_erlang = "~> 0.24"
gleam_json = "~> 0.7"
gleam_crypto = "~> 1.0"
glint = "~> 0.14"
gleam_otp = "~> 0.9"
ids = "~> 0.11"

[dev-dependencies]
gleeunit = "~> 1.0"
