name = "sprocket"
version = "0.1.3"
description = "A library for building live views and real-time server components in Gleam"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
repository = { type = "github", user = "bitbldr", repo = "sprocket" }
links = [{ title = "Website", href = "https://sprocket.live" }]

# Modules that should be considered "internal" and will not be included in
# generated documentation. Note this currently only affects documentation;
# public types and functions defined in these modules are still public.
#
# Items in this list are "globs" that are matched against module names. See:
# https://docs.rs/glob/latest/glob/struct.Pattern.html
internal_modules = [
  "docs",
  "docs/*",
  "sprocket/internal/*",
]

[dependencies]
gleam_stdlib = "~> 0.30"
gleam_http = "~> 3.2"
#mist = "~> 0.13.2"
mist = { path = "local/mist" }
gleam_erlang = "~> 0.18"
gleam_json = "~> 0.5"
gleam_crypto = "~> 0.3"
glint = "~> 0.11.4"

[dev-dependencies]
gleeunit = "~> 0.10"
